INSERT INTO UNIDAD (DESCRIPCION) VALUES ('entera');

INSERT INTO MATERIAL (NOMBRE,DESCRIPCION,PRECIO,STOCK_ACTUAL,STOCK_MINIMO,ID_UNIDAD) VALUES ('Ladrillos','Ladrillos Huecos',50,1000,200,1);

INSERT INTO DETALLE_PEDIDO (ID_MATERIAL,CANTIDAD) VALUES (1,600);

